before:
  hooks:
    - go mod tidy

builds:
  - main: ./cmd/pastiche
    id: pastiche
    binary: pastiche
    goos:
      - linux
      - windows
      - darwin
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X github.com/Carbonfrost/pastiche/pkg/internal/build.Version={{.Version}}

archives:
  - id: pastiche
    replacements:
      "386": i386
      amd64: x86_64
    format_overrides:
      - goos: windows
        format: zip

brews:
  - name: pastiche
    ids:
    - pastiche
    tap:
      owner: Carbonfrost
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    commit_msg_template: "Brew formula update for {{ .ProjectName }} version {{ .Tag }}"
    description: "Make requests to HTTP APIs using their OpenAPI schemas and definitions"
    homepage: "https://github.com/Carbonfrost/pastiche"

changelog:
  skip: true

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-dev"
