// Code generated by counterfeiter. DO NOT EDIT.
package clientfakes

import (
	"sync"

	"github.com/Carbonfrost/pastiche/pkg/client"
)

type FakeResponse struct {
	DataStub        func() (any, error)
	dataMutex       sync.RWMutex
	dataArgsForCall []struct {
	}
	dataReturns struct {
		result1 any
		result2 error
	}
	dataReturnsOnCall map[int]struct {
		result1 any
		result2 error
	}
	DocumentStub        func() (any, error)
	documentMutex       sync.RWMutex
	documentArgsForCall []struct {
	}
	documentReturns struct {
		result1 any
		result2 error
	}
	documentReturnsOnCall map[int]struct {
		result1 any
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeResponse) Data() (any, error) {
	fake.dataMutex.Lock()
	ret, specificReturn := fake.dataReturnsOnCall[len(fake.dataArgsForCall)]
	fake.dataArgsForCall = append(fake.dataArgsForCall, struct {
	}{})
	stub := fake.DataStub
	fakeReturns := fake.dataReturns
	fake.recordInvocation("Data", []interface{}{})
	fake.dataMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeResponse) DataCallCount() int {
	fake.dataMutex.RLock()
	defer fake.dataMutex.RUnlock()
	return len(fake.dataArgsForCall)
}

func (fake *FakeResponse) DataCalls(stub func() (any, error)) {
	fake.dataMutex.Lock()
	defer fake.dataMutex.Unlock()
	fake.DataStub = stub
}

func (fake *FakeResponse) DataReturns(result1 any, result2 error) {
	fake.dataMutex.Lock()
	defer fake.dataMutex.Unlock()
	fake.DataStub = nil
	fake.dataReturns = struct {
		result1 any
		result2 error
	}{result1, result2}
}

func (fake *FakeResponse) DataReturnsOnCall(i int, result1 any, result2 error) {
	fake.dataMutex.Lock()
	defer fake.dataMutex.Unlock()
	fake.DataStub = nil
	if fake.dataReturnsOnCall == nil {
		fake.dataReturnsOnCall = make(map[int]struct {
			result1 any
			result2 error
		})
	}
	fake.dataReturnsOnCall[i] = struct {
		result1 any
		result2 error
	}{result1, result2}
}

func (fake *FakeResponse) Document() (any, error) {
	fake.documentMutex.Lock()
	ret, specificReturn := fake.documentReturnsOnCall[len(fake.documentArgsForCall)]
	fake.documentArgsForCall = append(fake.documentArgsForCall, struct {
	}{})
	stub := fake.DocumentStub
	fakeReturns := fake.documentReturns
	fake.recordInvocation("Document", []interface{}{})
	fake.documentMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeResponse) DocumentCallCount() int {
	fake.documentMutex.RLock()
	defer fake.documentMutex.RUnlock()
	return len(fake.documentArgsForCall)
}

func (fake *FakeResponse) DocumentCalls(stub func() (any, error)) {
	fake.documentMutex.Lock()
	defer fake.documentMutex.Unlock()
	fake.DocumentStub = stub
}

func (fake *FakeResponse) DocumentReturns(result1 any, result2 error) {
	fake.documentMutex.Lock()
	defer fake.documentMutex.Unlock()
	fake.DocumentStub = nil
	fake.documentReturns = struct {
		result1 any
		result2 error
	}{result1, result2}
}

func (fake *FakeResponse) DocumentReturnsOnCall(i int, result1 any, result2 error) {
	fake.documentMutex.Lock()
	defer fake.documentMutex.Unlock()
	fake.DocumentStub = nil
	if fake.documentReturnsOnCall == nil {
		fake.documentReturnsOnCall = make(map[int]struct {
			result1 any
			result2 error
		})
	}
	fake.documentReturnsOnCall[i] = struct {
		result1 any
		result2 error
	}{result1, result2}
}

func (fake *FakeResponse) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeResponse) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ client.Response = new(FakeResponse)
