// Code generated by "stringer -type=ID -trimprefix=ID"; DO NOT EDIT.

package grpcclient

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[IDPlaintext-1]
	_ = x[IDDisableReflection-2]
	_ = x[IDProtoset-3]
	_ = x[IDHeader-4]
}

const _ID_name = "PlaintextDisableReflectionProtosetHeader"

var _ID_index = [...]uint8{0, 9, 26, 34, 40}

func (i ID) String() string {
	idx := int(i) - 1
	if i < 1 || idx >= len(_ID_index)-1 {
		return "ID(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ID_name[_ID_index[idx]:_ID_index[idx+1]]
}
